env:
  browser: true
  es6: true
extends:
  - eslint:recommended
  - plugin:vue/recommended
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  quotes:
    - error
    - single
  semi:
    - error
    - never
